### ISSUE TITLE
fail for number greater than max_int

### ISSUE THREAD

**Issue by newyangyang** [pjebs/optimus-go#2]
Hey, bro. I tested your code, but fail with number  greater than 2147483647(i.e. max_int in your code)  with `Encode(n uint64) uint64` . By _failure_ , I mean`i!=Decode(Encode(i))`

**Comment by pjebs** [comment]
It's meant to only work upto Max_Int.
My library is a port of PHP library: https://github.com/jenssegers/optimus

Due to PHP's unsigned int limitations, max_int is set to 2147483647: https://github.com/jenssegers/optimus/issues/17

If you want it to be larger (since Go can easily support larger), then fork this library and increase it to: `9223372036854775807 - 1` or `9223372036854775807` (can't remember which is correct) on Line 20: https://github.com/pjebs/optimus-go/blob/master/optimus.go#L20

**Comment by pjebs** [comment]
I noticed you changed it to `18446744073709551615`.
Check if it works for all numbers in uint64 range. It may not because https://github.com/newyangyang/optimus-go/blob/master/optimus.go#L96 casts it to int64.

So you have 2 options: 
1) Change max_int to the number in previous post OR
2) calculate your own modInverse externally (using Matlab, Mathematica or some other maths program) and use the `New()` function instead of `NewCalculated()`.

**Comment by newyangyang** [comment]
It's very nice of you, pjebs. I choose option 2, because this number is from a hash function which produces uint64. Option 2 is the right way. Thank you bro.

**Comment by pjebs** [comment]
Just remember your modInverse must satisfy this constraint:
`(PRIME * INVERSE) & MAXID == 1`

**Comment by k359792067** [comment]
I choose option 1, but not used, `i!=Decode(Encode(i))` can u give me a example?

**Comment by pjebs** [comment]
can you send me example of numbers you used.

**Comment by k359792067** [comment]
I update optimus.go
`var (
	MAX_INT uint64 = 9223372036854775807 - 1 
)`
and encode number 1571136437040550

       `o := optimus.New(1580030173, 59260789, 1163945558)

	new_id := o.Encode(1571136437040550)
	fmt.Println(new_id) //62820430328759832

	orig_id := o.Decode(new_id)

	fmt.Println(orig_id) //4796456803031922086`

**Comment by pjebs** [comment]
@k359792067 https://play.golang.org/p/3tSywB7HBAj

`o := optimus.New(1580030173, 59260789, 1163945558)`. The middle number must be the modinverse of the prime. Optimus comes with a built in function to calculate mod inverse.

It should have been `o := optimus.New(1580030173, 2589692097875951477, 1163945558)`

**Comment by k359792067** [comment]
@pjebs thank you man. And i have another question, orig_id (1571136437040550) has 16 digits, 
new_id (62820430328759832) has 17 digits. Is there any law?

**Comment by pjebs** [comment]
upto max_int

**Comment by zhoujin7** [comment]
> upto max_int

Is it really not possible to exceed the maximum int? Is it a limitation on this algorithm? The primary key type of the database I set up is bigint (64 bits).
