### ISSUE TITLE
Move GenerateSeed() to a separate sub-package

### ISSUE THREAD

**Issue by dolmen** [pjebs/optimus-go#4]
Use of `GenerateSeed()` is optional (and even discouraged). The code of this function brings a dependency on a full HTTP client in an otherwise small package.

Users of this library should not be forced to have this dependency. So it would be better to move the `GenerateSeed()` function to a separate package (suggestion: `github.com/pjebs/optimus-go/seed`).

**Comment by pjebs** [comment]
You are right. I will change it. If you could do a pull-request, that would be greatly appreciated.

**Comment by dolmen** [comment]
Well, I tried. But the code is not in a state that allows clean refactoring: the test suite randomly fails.

And also, #3 is an interesting proposal that is matching my request. It needs a review.

**Comment by pjebs** [comment]
I've refactored the code to move the generator into a subpackage.

The reason why the test occasionally fails is due to the `GenerateSeed()` function.
When it attempts to parse the downloaded text files containing the prime numbers, sometimes it does not extract the prime numbers correctly.

The text file is in this format:
```
15484099  15484123  15484141  15484153  15484187  15484199  15484201  15484211 

  15484219  15484223  15484243  15484247  15484279  15484333  15484363  15484387 

  15484393  15484409  15484421  15484453  15484457  15484459  15484471  15484489 

  15484517  15484519  15484549  15484559  15484591  15484627  15484631  15484643 

  15484661  15484697  15484709  15484723  15484769  15484771  15484783  15484817 

  15484823  15484873  15484877  15484879  15484901  15484919  15484939  15484951 

  15484961  15484999  15485039  15485053  15485059  15485077  15485083  15485143 

  15485161  15485179  15485191  15485221  15485243  15485251  15485257  15485273 

  15485287  15485291  15485293  15485299  15485311  15485321  15485339  15485341 

  15485357  15485363  15485383  15485389  15485401  15485411  15485429  15485441 

  15485447  15485471  15485473  15485497  15485537  15485539  15485543  15485549 

  15485557  15485567  15485581  15485609  15485611  15485621  15485651  15485653 

  15485669  15485677  15485689  15485711  15485737  15485747  15485761  15485773 

  15485783  15485801  15485807  15485837  15485843  15485849  15485857  15485863 
```

On some occasions, the number grabbed is not complete. Let say it tried to extract: `15485863`.
It may extract `1548586` instead. Since this number is not prime it panics.

**YOU DON'T NEED TO WORRY ABOUT THIS**
- The `GenerateSeed()` function is only for use in development time - not run time.
- If the extracted number is partial, the function **WILL ALWAYS** panic. You don't need to worry about it. You just run the function again to get your seeds.

I don't have time to fix the parser and since it's not important I left it "as is". If you want to give it a go, go ahead.

**Comment by pjebs** [comment]
**ALSO: ALWAYS DOUBLE CHECK THE SEEDS ANYWAY AS PER MY WARNING IN DOCUMENTATION**
